version: 2.1
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - sudo apt install -y build-essential
      - run: make all clean

workflows:
  version: 2
  build:
    jobs:
      - build
